import { ZipReader, ZipWriter, BlobReader, BlobWriter, TextWriter } from 'https://cdn.jsdelivr.net/npm/@zip.js/zip.js@2.7.57/+esm';

const $ = id => document.getElementById(id);
const canvas = $('view'), ctx = canvas.getContext('2d');
const NODE_TYPES = ['Node2D','CharacterBody2D','StaticBody2D','Area2D','Sprite2D','AnimatedSprite2D','Camera2D','CollisionShape2D','CollisionPolygon2D','TileMap','TileMapLayer','AnimationPlayer','CanvasLayer','Control','Label','Button','Marker2D','River'];
const nodeIcons = {Node:'◇',Node2D:'◇',CharacterBody2D:'●',StaticBody2D:'■',Area2D:'◎',Sprite2D:'▧',AnimatedSprite2D:'▤',Camera2D:'⌾',CollisionShape2D:'◇',CollisionPolygon2D:'◇',TileMap:'▦',TileMapLayer:'▦',AnimationPlayer:'◌',CanvasLayer:'▱',Control:'□',Label:'T',Button:'▣',Marker2D:'⌾',River:'≋'};
const state = {
  zip:null,entries:new Map(),root:'',project:{},files:[],scene:null,selected:null,tool:'select',mode:'2d',playing:false,grid:true,zoom:1,
  camera:{x:550,y:340,limits:null},player:{x:550,y:340,speed:220,r:13},keys:new Set(),last:performance.now(),fps:60,frame:0,
  runtime:{entities:new Map(),areas:new Map(),events:[],startedAt:0,animationTime:0},
  drag:null,cacheBytes:0,cache:new Map(),dirty:false,errors:[],undo:[],redo:[],projectModel:{format:'ninja-engine',version:'0.1',project:{},scenes:[],resources:[],scripts:[],settings:{}}
};
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const escapeAttr=escapeHtml;
function ext(p){const i=p.lastIndexOf('.');return i<0?'':p.slice(i).toLowerCase();}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function archiveSizeLabel(n){return n<1048576?`${(n/1024).toFixed(0)} KB`:`${(n/1048576).toFixed(1)} MB`;}
function log(msg,level='info'){const icon=level==='error'?'✕':level==='warn'?'!':'●';$('console').insertAdjacentHTML('beforeend',`<div class="log-${level}"><i>${icon}</i> ${escapeHtml(msg)}</div>`);$('console').scrollTop=$('console').scrollHeight;if(level==='error'){state.errors.push(msg);$('errorCount').textContent=state.errors.length;$('errors').innerHTML=state.errors.map(escapeHtml).map(x=>`<div class="log-error">✕ ${x}</div>`).join('');}}
function markDirty(){state.dirty=true;$('dirtyState').textContent='● Modified';}
function clone(v){return JSON.parse(JSON.stringify(v));}
function snapshot(){return {scene:clone(state.scene),selectedId:state.selected?.id||null};}
function restore(s){state.scene=clone(s.scene);state.selected=state.scene.nodes.find(n=>n.id===s.selectedId)||null;renderAll();}
function commit(label,before){state.undo.push({label,before,after:snapshot()});if(state.undo.length>100)state.undo.shift();state.redo=[];markDirty();}
function undo(){const c=state.undo.pop();if(!c)return;state.redo.push(c);restore(c.before);log(`Undo: ${c.label}`);}
function redo(){const c=state.redo.pop();if(!c)return;state.undo.push(c);restore(c.after);log(`Redo: ${c.label}`);}
function node(type,name,x=550,y=340,w=64,h=48,parent=''){return {id:crypto.randomUUID(),name:name||type,type,parent,x,y,w,h,rotation:0,scaleX:1,scaleY:1,visible:true,properties:{},metadata:{},source:''};}
function rootForScene(s){return s.root||{id:'root',name:s.name||'Main',type:'Node2D',parent:null,x:0,y:0,w:0,h:0,rotation:0,visible:true,properties:{},metadata:{}};}
function setScene(s){state.scene=s;state.scene.root=rootForScene(s);state.selected=null;state.undo=[];state.redo=[];renderAll();}

async function refreshConnections(){
  if(!window.ninjaBridge){$('connectionSummary').textContent='Connections: Web mode';return;}
  const c=await window.ninjaBridge.connections();
  const set=(id,x)=>$(id).textContent=x.configured?'Configured':'Not configured';
  set('aiStatus',c.ai);set('notionStatus',c.notion);set('githubStatus',c.github);
  $('connectionSummary').textContent=`AI ${c.ai.configured?'✓':'—'} · Notion ${c.notion.configured?'✓':'—'} · GitHub ${c.github.configured?'✓':'—'}`;
}
async function testConnection(service,id){
  if(!window.ninjaBridge)return; const r=await window.ninjaBridge.testConnection(service); $(id).textContent=r.message|| (r.ok?'Connected':'Unavailable'); log(`${service}: ${r.message}`,r.ok?'info':'warn');
}
$('connectionsBtn').onclick=()=>{const p=$('connectionsPanel');p.hidden=!p.hidden;if(!p.hidden)refreshConnections();};
$('closeConnectionsBtn').onclick=()=>$('connectionsPanel').hidden=true;
$('mobileMenuBtn').onclick=()=>{document.querySelector('.left-panel').classList.toggle('mobile-open');document.querySelector('.right-panel').classList.remove('mobile-open');};
$('mobileInspectorBtn').onclick=()=>{document.querySelector('.right-panel').classList.toggle('mobile-open');document.querySelector('.left-panel').classList.remove('mobile-open');};
$('aiConnectBtn').onclick=()=>testConnection('ai','aiStatus');$('notionConnectBtn').onclick=()=>testConnection('notion','notionStatus');$('githubConnectBtn').onclick=()=>testConnection('github','githubStatus');
$('openBtn').onclick=()=>$('zipInput').click();
$('zipInput').onchange=e=>e.target.files[0]&&openZip(e.target.files[0]);
$('playBtn').onclick=()=>{resetRuntime();state.playing=true;state.mode='game';syncModes();log('Runtime started.');};
$('stopBtn').onclick=()=>{state.playing=false;state.mode='2d';syncModes();log('Play mode stopped.');};
$('gridBtn').onclick=()=>{state.grid=!state.grid;$('gridBtn').classList.toggle('active',state.grid);draw();};
$('fitBtn').onclick=()=>{state.camera={x:550,y:340};state.zoom=1;$('zoomLabel').textContent='100%';draw();};
$('zoomInBtn').onclick=()=>setZoom(state.zoom*1.15);$('zoomOutBtn').onclick=()=>setZoom(state.zoom/1.15);
$('saveBtn').onclick=saveNinjaProject;$('exportBtn').onclick=exportProject;$('newSceneBtn').onclick=newScene;$('deleteBtn').onclick=deleteSelected;$('duplicateBtn').onclick=duplicateSelected;
$('newNodeBtn').onclick=()=>{const before=snapshot();const n=addNode('Node2D');state.selected=n;commit('Create Node2D',before);renderAll();};$('newTileMapBtn').onclick=()=>{const before=snapshot();const n=addNode('TileMap','World TileMap',550,340,640,448);state.selected=n;commit('Create TileMap',before);renderAll();};$('newAnimBtn').onclick=()=>{const before=snapshot();const n=addNode('AnimatedSprite2D','Animated Sprite',550,340,64,64);state.selected=n;commit('Create AnimatedSprite2D',before);renderAll();};
$('searchFiles').oninput=renderFiles;$('searchAssets').oninput=renderAssets;
for(const b of document.querySelectorAll('[data-tool]'))b.onclick=()=>{state.tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));};
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{state.mode=b.dataset.mode;if(state.mode!=='game')state.playing=false;syncModes();};
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>switchLeftTab(b.dataset.tab);
for(const b of document.querySelectorAll('[data-bottom]'))b.onclick=()=>switchBottomTab(b.dataset.bottom);
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();state.keys.add(k);if(k==='delete')deleteSelected();if(k==='z'&&(e.ctrlKey||e.metaKey)){e.preventDefault();e.shiftKey?redo():undo();}if(k==='y'&&(e.ctrlKey||e.metaKey)){e.preventDefault();redo();}if(k==='d'&&(e.ctrlKey||e.metaKey)){e.preventDefault();duplicateSelected();}if(k==='s'&&(e.ctrlKey||e.metaKey)){e.preventDefault();saveNinjaProject();}if(k==='escape'){state.selected=null;renderAll();}});
window.addEventListener('keyup',e=>state.keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>state.keys.clear());
canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(state.zoom*(e.deltaY<0?1.1:.9),e);},{passive:false});
canvas.addEventListener('pointerdown',e=>{const p=screenToWorld(e);if(state.mode==='game')return;if(state.tool==='select'||state.tool==='move'){const hit=findNodeAt(p.x,p.y);state.selected=hit;if(hit&&state.tool==='move')state.drag={node:hit,dx:p.x-hit.x,dy:p.y-hit.y,before:snapshot()};renderAll();}else{const before=snapshot();let n=null;if(state.tool==='rect')n=addNode('StaticBody2D','StaticBody2D',p.x,p.y,96,64);if(state.tool==='collision')n=addNode('CollisionShape2D','CollisionShape2D',p.x,p.y,64,48);if(state.tool==='river')n=addNode('River','River',p.x,p.y,240,120);if(state.tool==='spawn')n=addNode('Marker2D','Marker2D',p.x,p.y,32,32);if(n){state.selected=n;commit(`Create ${n.type}`,before);renderAll();}if(state.tool==='tilepaint'&&state.selected?.type==='TileMap'){paintTile(state.selected,p.x,p.y);renderAll();}}});
canvas.addEventListener('pointermove',e=>{const p=screenToWorld(e);$('coord').textContent=`x: ${Math.round(p.x)}  y: ${Math.round(p.y)}`;if(state.drag){setLocalFromWorld(state.drag.node,p.x-state.drag.dx,p.y-state.drag.dy);markDirty();renderInspector();draw();}});
canvas.addEventListener('pointerup',()=>{if(state.drag){commit(`Move ${state.drag.node.name}`,state.drag.before);state.drag=null;}});canvas.addEventListener('pointerleave',()=>{if(state.drag){commit(`Move ${state.drag.node.name}`,state.drag.before);state.drag=null;}});
function syncModes(){document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode===state.mode));draw();}
function switchLeftTab(tab){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));$('scenePane').hidden=tab!=='scene';$('filesPane').hidden=tab!=='files';}
function switchBottomTab(tab){document.querySelectorAll('[data-bottom]').forEach(x=>x.classList.toggle('active',x.dataset.bottom===tab));$('console').hidden=tab!=='output';$('debugger').hidden=tab!=='debugger';$('errors').hidden=tab!=='errors';}
function setZoom(z){state.zoom=clamp(z,.35,3);$('zoomLabel').textContent=`${Math.round(state.zoom*100)}%`;draw();}
function screenToWorld(e){const r=canvas.getBoundingClientRect(),sx=(e.clientX-r.left)*canvas.width/r.width,sy=(e.clientY-r.top)*canvas.height/r.height;return{x:(sx-canvas.width/2)/state.zoom+state.camera.x,y:(sy-canvas.height/2)/state.zoom+state.camera.y};}
function addNode(type,name,x=550,y=340,w=70,h=55,parent=''){const n=node(type,name,x,y,w,h,parent);if(type==='TileMap'||type==='TileMapLayer'){n.properties={tileSize:32,columns:20,rows:14,cells:{},source:'procedural-grid'};}if(type==='AnimatedSprite2D'){n.properties={frames:4,frameDuration:0.14,loop:true,animation:'default'};}state.scene.nodes.push(n);return n;}
function paintTile(tile,x,y){const wt=worldTransform(tile);const size=Number(tile.properties?.tileSize)||32;const col=Math.floor((x-wt.x+tile.w/2)/size),row=Math.floor((y-wt.y+tile.h/2)/size);if(col<0||row<0)return;const cols=Math.max(1,Math.floor(tile.w/size)),rows=Math.max(1,Math.floor(tile.h/size));if(col>=cols||row>=rows)return;tile.properties=tile.properties||{};tile.properties.cells=tile.properties.cells||{};const key=`${col},${row}`;tile.properties.cells[key]=tile.properties.cells[key]?0:1;markDirty();}
function tileCells(tile){return tile.properties?.cells||{};}
function descendants(id){const out=[];const q=[id];while(q.length){const p=q.shift();for(const n of state.scene.nodes.filter(n=>n.parent===p)){out.push(n);q.push(n.id);}}return out;}
function getNode(id){return id==='root'?rootForScene(state.scene):state.scene.nodes.find(n=>n.id===id)||null;}
function worldTransform(n,seen=new Set()){if(!n)return{x:0,y:0,rotation:0,sx:1,sy:1};if(seen.has(n.id))return{x:n.x||0,y:n.y||0,rotation:n.rotation||0,sx:n.scaleX??1,sy:n.scaleY??1};seen.add(n.id);const p=n.parent?getNode(n.parent):null;if(!p)return{x:n.x||0,y:n.y||0,rotation:n.rotation||0,sx:n.scaleX??1,sy:n.scaleY??1};const pw=worldTransform(p,seen),r=(pw.rotation||0)*Math.PI/180, lx=(n.x||0)*(pw.sx??1), ly=(n.y||0)*(pw.sy??1);return{x:(pw.x||0)+lx*Math.cos(r)-ly*Math.sin(r),y:(pw.y||0)+lx*Math.sin(r)+ly*Math.cos(r),rotation:(pw.rotation||0)+(n.rotation||0),sx:(pw.sx??1)*(n.scaleX??1),sy:(pw.sy??1)*(n.scaleY??1)};}
function setLocalFromWorld(n,wx,wy){const p=n.parent?getNode(n.parent):null;if(!p){n.x=wx;n.y=wy;return;}const pw=worldTransform(p),r=-(pw.rotation||0)*Math.PI/180,dx=wx-(pw.x||0),dy=wy-(pw.y||0);n.x=(dx*Math.cos(r)-dy*Math.sin(r))/(pw.sx??1);n.y=(dx*Math.sin(r)+dy*Math.cos(r))/(pw.sy??1);}

function deleteSelected(){if(!state.selected)return;const before=snapshot(),id=state.selected.id;const doomed=new Set([id,...descendants(id).map(n=>n.id)]);state.scene.nodes=state.scene.nodes.filter(n=>!doomed.has(n.id));state.selected=null;commit('Delete node',before);renderAll();}
function duplicateSelected(){if(!state.selected)return;const before=snapshot(),o=state.selected,n=clone(o);n.id=crypto.randomUUID();n.name=`${o.name}_copy`;n.x+=24;n.y+=24;state.scene.nodes.push(n);state.selected=n;commit('Duplicate node',before);renderAll();}
function newScene(){const before=state.scene?snapshot():null;setScene({path:'',name:'New Scene',root:node('Node2D','NewScene',0,0,0,0,''),nodes:[]});state.scene.root.id='root';markDirty();if(before)state.undo=[];log('New scene created.');}
function findNodeAt(x,y){for(let i=state.scene.nodes.length-1;i>=0;i--){const n=state.scene.nodes[i];if(!n.visible)continue;const w=worldTransform(n),a=(w.rotation||0)*Math.PI/180,dx=x-w.x,dy=y-w.y,rx=dx*Math.cos(a)+dy*Math.sin(a),ry=-dx*Math.sin(a)+dy*Math.cos(a);if(Math.abs(rx)<=n.w*(w.sx??1)/2&&Math.abs(ry)<=n.h*(w.sy??1)/2)return n;}return null;}

async function openZip(file){
  state.zip=file;state.entries.clear();state.cache.clear();state.cacheBytes=0;state.errors=[];state.undo=[];state.redo=[];$('statusText').textContent='Reading archive…';$('projectStatus').textContent='Importing…';log(`Opening ${file.name}`);
  try{const reader=new ZipReader(new BlobReader(file));for(const e of await reader.getEntries())state.entries.set(e.filename,e);await reader.close();state.files=[...state.entries.keys()].sort((a,b)=>a.localeCompare(b));state.root=detectRoot();const pp=state.root+'project.godot';state.project=state.entries.has(pp)?parseGodot(await readText(pp)):{name:file.name.replace(/\.zip$/i,'')};state.projectModel.project=clone(state.project);$('projectStatus').textContent=state.project.name||file.name;$('memory').textContent=archiveSizeLabel(file.size);$('projectInfo').innerHTML=`<div><b>${escapeHtml(state.project.name||file.name)}</b></div><div>${state.entries.size.toLocaleString()} files</div><div>Godot features: ${escapeHtml(state.project.features||'unknown')}</div><div class="muted">Ninja intermediate model active</div>`;renderFiles();renderAssets();if(state.project.main_scene&&state.entries.has(resolvePath(state.project.main_scene)))await loadScene(resolvePath(state.project.main_scene));else refreshConnections();
setScene({path:'',name:'Main',root:node('Node2D','Main',0,0,0,0,''),nodes:[]});$('statusText').textContent='Project imported';log(`Indexed ${state.entries.size.toLocaleString()} archive entries.`);await buildCompatibilityReport();}
  catch(err){$('statusText').textContent='Import failed';log(err.message,'error');console.error(err);}
}
function detectRoot(){const keys=[...state.entries.keys()];if(keys.includes('project.godot'))return '';const k=keys.find(x=>x.endsWith('/project.godot'));return k?k.slice(0,-'project.godot'.length):'';}
function resolvePath(p){if(p.startsWith('res://'))return state.root+p.slice(6);return state.root+p;}
async function readText(path){const e=state.entries.get(path);if(!e)throw new Error(`Missing archive entry: ${path}`);if(state.cache.has(path))return state.cache.get(path).text;const text=await e.getData(new TextWriter());cachePut(path,{text,bytes:text.length*2});return text;}
function cachePut(path,value){state.cache.set(path,value);state.cacheBytes+=value.bytes||0;const MAX=64*1024*1024;while(state.cacheBytes>MAX&&state.cache.size>1){const k=state.cache.keys().next().value,v=state.cache.get(k);state.cache.delete(k);state.cacheBytes-=v.bytes||0;}$('memory').textContent=`cache ${archiveSizeLabel(state.cacheBytes)}`;}
function unquote(s){const t=s.trim();if(/^"[\s\S]*"$/.test(t))try{return JSON.parse(t);}catch{}return t;}
function parseGodot(t){const p={settings:{}};for(const raw of t.split(/\r?\n/)){const line=raw.trim();let m=line.match(/^config\/name\s*=\s*"(.*)"/);if(m)p.name=m[1];m=line.match(/^run\/main_scene\s*=\s*"(.*)"/);if(m)p.main_scene=m[1];m=line.match(/^config\/features\s*=\s*PackedStringArray\((.*)\)/);if(m)p.features=m[1];m=line.match(/^([^#=]+?)\s*=\s*(.+)$/);if(m&&!/^config\/name|^run\/main_scene|^config\/features/.test(line))p.settings[m[1].trim()]=unquote(m[2]);}return p;}
function splitTop(s){const out=[];let cur='',depth=0,quote=false,esc=false;for(const ch of s){if(esc){cur+=ch;esc=false;continue}if(ch==='\\'){cur+=ch;esc=true;continue}if(ch==='"'){quote=!quote;cur+=ch;continue}if(!quote&&(ch==='('||ch==='['||ch==='{'))depth++;if(!quote&&(ch===')'||ch===']'||ch==='}'))depth--;if(!quote&&depth===0&&ch===','){out.push(cur.trim());cur='';}else cur+=ch;}if(cur.trim())out.push(cur.trim());return out;}
function parseTyped(v){v=v.trim();if(v==='true')return true;if(v==='false')return false;if(v==='null')return null;if(/^[-+]?\d+(\.\d+)?$/.test(v))return Number(v);if(/^Vector2\(/.test(v)){const a=splitTop(v.slice(v.indexOf('(')+1,-1));return {__type:'Vector2',x:Number(a[0]),y:Number(a[1])};}if(/^Vector2i\(/.test(v)){const a=splitTop(v.slice(v.indexOf('(')+1,-1));return {__type:'Vector2i',x:Number(a[0]),y:Number(a[1])};}if(/^Color\(/.test(v))return {__type:'Color',raw:v};if(/^ExtResource\("([^"]+)"\)/.test(v))return {__type:'ExtResource',id:v.match(/^ExtResource\("([^"]+)"\)/)[1]};if(/^SubResource\("([^"]+)"\)/.test(v))return {__type:'SubResource',id:v.match(/^SubResource\("([^"]+)"\)/)[1]};if(/^PackedStringArray\(/.test(v))return splitTop(v.slice(v.indexOf('(')+1,-1)).map(parseTyped);if(/^Array\[/.test(v)||/^\[/.test(v))return splitTop(v.slice(v.indexOf('[')+1,-1)).map(parseTyped);if(/^"[\s\S]*"$/.test(v))try{return JSON.parse(v);}catch{}return v;}
function parseTscn(text,path){
  const lines=text.split(/\r?\n/), extResources={}, subResources={}, nodes=[], signals=[]; let section=null, current=null;
  for(const raw of lines){const line=raw.trim();if(!line||line.startsWith(';'))continue;
    let m=line.match(/^\[ext_resource\s+(.+)\]$/); if(m){const a=parseHeaderAttrs(m[1]);extResources[a.id||String(Object.keys(extResources).length+1)]={type:a.type||'',path:a.path||'',id:a.id||''};continue;}
    m=line.match(/^\[sub_resource\s+(.+)\]$/); if(m){const a=parseHeaderAttrs(m[1]);current={type:a.type||'',id:a.id||String(Object.keys(subResources).length+1),properties:{}};subResources[current.id]=current;section='sub';continue;}
    m=line.match(/^\[node\s+(.+)\]$/); if(m){const a=parseHeaderAttrs(m[1]);current={id:crypto.randomUUID(),name:a.name||'Node',type:a.type||'Node',parent:a.parent||'',x:0,y:0,w:64,h:48,rotation:0,visible:true,properties:{},metadata:{},source:a.instance||''};nodes.push(current);section='node';continue;}
    m=line.match(/^\[connection\s+(.+)\]$/); if(m){signals.push(parseHeaderAttrs(m[1]));section='connection';continue;}
    if(line.startsWith('[')){section=null;current=null;continue;}
    m=line.match(/^([^=]+?)\s*=\s*(.+)$/);if(!m||!current)continue;const key=m[1].trim(), value=parseTyped(m[2]);
    if(section==='node'){current.properties[key]=value;if(key==='position'&&value?.__type==='Vector2'){current.x=value.x;current.y=value.y;}else if(key==='rotation')current.rotation=Number(value)*180/Math.PI;else if(key==='visible')current.visible=Boolean(value);else if(key==='size'&&value?.__type==='Vector2'){current.w=value.x;current.h=value.y;}}
    else if(section==='sub')current.properties[key]=value;
  }
  const root=nodes.find(n=>!n.parent)||nodes[0]||node('Node2D','Main',0,0,0,0,'');
  const list=nodes.filter(n=>n!==root);const map=new Map(nodes.map(n=>[n.name,n]));
  for(const n of list){if(n.parent==='.')n.parent=root.id;else if(n.parent){const parentName=n.parent.split('/').pop();const p=map.get(parentName);if(p)n.parent=p.id;}}
  return {path,name:path.split('/').pop().replace(/\.tscn$/i,''),root,nodes:list,resources:{extResources,subResources},signals,format:3};
}
function parseHeaderAttrs(s){const a={};for(const part of splitHeader(s)){const m=part.match(/^([\w/]+)=(.*)$/);if(m)a[m[1]]=unquote(m[2]);}return a;}
function splitHeader(s){const out=[];let cur='',q=false,esc=false;for(const ch of s){if(esc){cur+=ch;esc=false;continue}if(ch==='\\'){cur+=ch;esc=true;continue}if(ch==='"'){q=!q;cur+=ch;continue}if(!q&&/\s/.test(ch)){if(cur){out.push(cur);cur='';}}else cur+=ch;}if(cur)out.push(cur);return out;}

async function loadScene(path){if(!state.entries.has(path)){log(`Scene not found: ${path}`,'error');return;}try{const text=await readText(path);if(ext(path)!=='.tscn'){log(`Unsupported scene format: ${ext(path)}`,'warn');return;}const parsed=parseTscn(text,path);setScene(parsed);state.projectModel.scenes=state.projectModel.scenes.filter(s=>s.path!==path);state.projectModel.scenes.push(clone(parsed));$('sceneName').textContent=state.scene.name;log(`Loaded scene ${path}: ${state.scene.nodes.length+1} nodes, ${Object.keys(parsed.resources.extResources).length} external resources.`);}
catch(e){log(`Scene parse failed: ${e.message}`,'error');}}
function renderAll(){renderSceneTree();renderInspector();renderFiles();draw();$('sceneName').textContent=state.scene?.name||'Untitled Scene';$('dirtyState').textContent=state.dirty?'● Modified':'';}
function renderSceneTree(){const root=rootForScene(state.scene||{});const rows=[];function walk(parent,depth){const children=state.scene.nodes.filter(n=>n.parent===parent);for(const n of children){rows.push({n,depth});walk(n.id,depth+1);}}rows.push({n:root,depth:0});walk(root.id,1);$('sceneTree').innerHTML=rows.map((r,i)=>`<div class="tree-row ${r.n===state.selected?'selected':''}" data-id="${r.n.id}"><span class="tree-indent">${r.depth?'↳':'▾'}</span><span class="tree-icon">${nodeIcons[r.n.type]||'◇'}</span><span class="tree-label">${escapeHtml(r.n.name)}</span><span class="node-type">${escapeHtml(r.n.type)}</span></div>`).join('');document.querySelectorAll('#sceneTree .tree-row').forEach(el=>el.onclick=()=>{state.selected=state.scene.nodes.find(n=>n.id===el.dataset.id)||null;renderAll();});$('objectCount').textContent=state.scene.nodes.length;}
function tileInspector(n){if(!['TileMap','TileMapLayer'].includes(n.type))return '';const ts=Number(n.properties?.tileSize)||32;const cells=Object.keys(tileCells(n)).length;return `<div class=\"field-group\"><label>Tile Size</label><input id=\"tileSizeInput\" type=\"number\" value=\"${ts}\"></div><div class=\"field-group\"><label>Painted Cells</label><div class=\"muted\">${cells} cells · use ▦ tool</div></div>`;}
function renderInspector(){const o=state.selected;$('selectedType').textContent=o?o.type:'—';if(!o){$('inspector').innerHTML='<div class="empty-state"><div class="empty-icon">◇</div><strong>Select a node</strong><span>Properties will appear here.</span></div>';return;}const parents=[rootForScene(state.scene),...state.scene.nodes.filter(n=>n.id!==o.id)];$('inspector').innerHTML=`${tileInspector(o)}<div class="property-group"><div class="property-header">NODE</div><div class="property"><label>Name</label><input data-p="name" value="${escapeAttr(o.name)}"></div><div class="property"><label>Type</label><select data-p="type">${NODE_TYPES.map(t=>`<option ${t===o.type?'selected':''}>${t}</option>`).join('')}</select></div><div class="property"><label>Parent</label><select data-p="parent"><option value="">${escapeHtml(rootForScene(state.scene).name)}</option>${parents.filter(p=>p.id&&p.id!==o.id).map(p=>`<option value="${p.id}" ${o.parent===p.id?'selected':''}>${escapeHtml(p.name)}</option>`).join('')}</select></div><div class="property"><label>Source</label><input value="${escapeAttr(o.source||'Internal')}" disabled></div></div><div class="property-group"><div class="property-header">TRANSFORM</div>${['x','y','w','h','rotation','scaleX','scaleY'].map(k=>`<div class="property"><label>${k.toUpperCase()}</label><input type="number" step="0.1" data-p="${k}" value="${o[k]??0}"></div>`).join('')}</div><div class="property-group"><div class="property-header">VISIBILITY</div><div class="property"><label>Visible</label><select data-p="visible"><option value="true" ${o.visible?'selected':''}>True</option><option value="false" ${!o.visible?'selected':''}>False</option></select></div></div><div class="property-group"><div class="property-header">PROPERTIES</div><div class="property-json"><code>${escapeHtml(JSON.stringify(o.properties,null,2))}</code></div></div>`;
  document.querySelectorAll('#inspector [data-p]').forEach(el=>el.onchange=()=>{const before=snapshot(),p=el.dataset.p;if(p==='visible')o[p]=el.value==='true';else if(['x','y','w','h','rotation','scaleX','scaleY'].includes(p))o[p]=Number(el.value);else if(p==='type')o[p]=el.value;else o[p]=el.value;commit(`Change ${p}`,before);renderAll();});
}
function renderFiles(){const q=$('searchFiles').value.toLowerCase();const arr=state.files.filter(k=>k.toLowerCase().includes(q)).slice(0,1000);$('fileList').innerHTML=arr.length?arr.map(k=>`<div class="file-row" title="${escapeAttr(k)}"><span>${fileIcon(k)}</span><span>${escapeHtml(k)}</span></div>`).join(''):'<div class="muted">No matching files.</div>';}
function renderAssets(){const q=$('searchAssets').value.toLowerCase();const arr=state.files.filter(k=>/\.(png|jpe?g|webp|svg|ogg|wav|mp3|ttf|woff2?|tscn|tres|res)$/i.test(k)&&k.toLowerCase().includes(q)).slice(0,500);$('assetCount').textContent=arr.length;$('assetList').innerHTML=arr.length?arr.map(k=>`<div class="asset"><span class="asset-icon">${fileIcon(k)}</span><span title="${escapeAttr(k)}">${escapeHtml(k.split('/').pop())}</span></div>`).join(''):'<div class="muted">No assets found.</div>';}
function fileIcon(k){const e=ext(k);return e==='.tscn'?'◇':e==='.gd'?'G':e==='.png'||e==='.jpg'||e==='.jpeg'||e==='.webp'?'▧':e==='.ogg'||e==='.wav'||e==='.mp3'?'♫':e==='.tres'||e==='.res'?'◆':'•';}
async function buildCompatibilityReport(){const counts={supported:0,partial:0,unsupported:0};const details=[];for(const p of state.files){const e=ext(p);let status='unsupported';if(['.tscn','.godot'].includes(e))status='supported';else if(['.tres','.res','.gd','.png','.jpg','.jpeg','.webp','.svg','.ogg','.wav','.mp3','.ttf','.woff','.woff2'].includes(e))status='partial';counts[status]++;details.push({path:p,status});}state.projectModel.compatibility={...counts,details};buildResourceModel();log(`Compatibility scan: ${counts.supported} supported, ${counts.partial} partial, ${counts.unsupported} unsupported.`);}
function colliders(){return state.scene.nodes.filter(n=>n.visible!==false&&['StaticBody2D','CollisionShape2D','CollisionPolygon2D','River'].includes(n.type));}
function rectWorld(o){const t=worldTransform(o);return {x:t.x,y:t.y,w:Math.abs((o.w||0)*(t.sx||1)),h:Math.abs((o.h||0)*(t.sy||1))};}
function overlaps(a,b,pad=0){const A=rectWorld(a),B=typeof b==='object'&&b.w!==undefined?b:{x:b.x,y:b.y,w:b.r*2,h:b.r*2};return Math.abs(A.x-B.x)*2 < A.w+B.w+pad*2 && Math.abs(A.y-B.y)*2 < A.h+B.h+pad*2;}
function blocked(nx,ny){const r=state.player.r;for(const o of colliders()){const b=rectWorld(o);if(Math.abs(nx-b.x)*2 < b.w+2*r && Math.abs(ny-b.y)*2 < b.h+2*r)return true;}return false;}
function entityPosition(n){const t=worldTransform(n);return {x:t.x,y:t.y};}
function resetRuntime(){state.runtime={entities:new Map(),areas:new Map(),events:[],startedAt:performance.now(),animationTime:0};const chars=state.scene.nodes.filter(n=>n.type==='CharacterBody2D');const spawn=state.scene.nodes.find(n=>n.type==='Marker2D'&&n.properties?.spawn===true)||chars[0];const pos=spawn?entityPosition(spawn):{x:550,y:340};state.player.x=pos.x;state.player.y=pos.y;state.camera.x=pos.x;state.camera.y=pos.y;for(const n of state.scene.nodes){if(n.type==='CharacterBody2D')state.runtime.entities.set(n.id,{id:n.id,node:n,x:entityPosition(n).x,y:entityPosition(n).y,vx:0,vy:0});if(n.type==='Area2D')state.runtime.areas.set(n.id,new Set());}}
function areaEvents(){for(const area of state.scene.nodes.filter(n=>n.type==='Area2D'&&n.visible!==false)){const inside=overlaps(area,{x:state.player.x,y:state.player.y,w:state.player.r*2,h:state.player.r*2});const set=state.runtime.areas.get(area.id)||new Set();const key='player';if(inside&&!set.has(key)){set.add(key);state.runtime.events.unshift(`${area.name}: body_entered(player)`);state.runtime.events=state.runtime.events.slice(0,30);}else if(!inside&&set.has(key)){set.delete(key);state.runtime.events.unshift(`${area.name}: body_exited(player)`);state.runtime.events=state.runtime.events.slice(0,30);}state.runtime.areas.set(area.id,set);}}
function clampCamera(){const l=state.camera.limits;if(!l)return;const hw=canvas.width/(2*state.zoom),hh=canvas.height/(2*state.zoom);state.camera.x=clamp(state.camera.x,l.left+hw,l.right-hw);state.camera.y=clamp(state.camera.y,l.top+hh,l.bottom-hh);}
function updateRuntime(dt){if(!state.playing)return;let dx=0,dy=0;if(state.keys.has('w')||state.keys.has('arrowup'))dy--;if(state.keys.has('s')||state.keys.has('arrowdown'))dy++;if(state.keys.has('a')||state.keys.has('arrowleft'))dx--;if(state.keys.has('d')||state.keys.has('arrowright'))dx++;if(dx||dy){const l=Math.hypot(dx,dy);dx/=l;dy/=l;const sp=state.player.speed*dt;const nx=state.player.x+dx*sp,ny=state.player.y+dy*sp;if(!blocked(nx,state.player.y))state.player.x=nx;if(!blocked(state.player.x,ny))state.player.y=ny;}state.camera.x+=(state.player.x-state.camera.x)*Math.min(1,dt*8);state.camera.y+=(state.player.y-state.camera.y)*Math.min(1,dt*8);clampCamera();areaEvents();}
function draw(){if(!state.scene)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#080c12';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(canvas.width/2,canvas.height/2);ctx.scale(state.zoom,state.zoom);ctx.translate(-state.camera.x,-state.camera.y);if(state.grid){ctx.strokeStyle='#16232e';ctx.lineWidth=1/state.zoom;const step=32,x0=Math.floor((state.camera.x-canvas.width/state.zoom/2)/step)*step,y0=Math.floor((state.camera.y-canvas.height/state.zoom/2)/step)*step;for(let x=x0;x<state.camera.x+canvas.width/state.zoom/2;x+=step){ctx.beginPath();ctx.moveTo(x,state.camera.y-canvas.height/state.zoom/2);ctx.lineTo(x,state.camera.y+canvas.height/state.zoom/2);ctx.stroke();}for(let y=y0;y<state.camera.y+canvas.height/state.zoom/2;y+=step){ctx.beginPath();ctx.moveTo(state.camera.x-canvas.width/state.zoom/2,y);ctx.lineTo(state.camera.x+canvas.width/state.zoom/2,y);ctx.stroke();}}for(const o of state.scene?.nodes||[])drawNode(o);if(state.mode==='game'||state.playing){ctx.fillStyle='#e6a0a0';ctx.beginPath();ctx.arc(state.player.x,state.player.y,state.player.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.stroke();}ctx.restore();if(state.mode==='debug'){ctx.fillStyle='#b9c8da';ctx.font='11px ui-monospace';ctx.fillText(`DEBUG nodes:${state.scene?.nodes.length||0} colliders:${colliders().length} entities:${state.runtime.entities.size} player:${Math.round(state.player.x)},${Math.round(state.player.y)} vel:${state.player.speed}`,14,24);}}
function drawNode(o){if(!o.visible)return;ctx.save();const wt=worldTransform(o);ctx.translate(wt.x,wt.y);ctx.rotate((wt.rotation||0)*Math.PI/180);ctx.scale(wt.sx??1,wt.sy??1);ctx.globalAlpha=o===state.selected?.85:1;let fill='#2d5b37';if(o.type==='River')fill='#286d99';else if(o.type==='StaticBody2D'||o.type.includes('Collision'))fill='#46515e';else if(o.type==='Marker2D')fill='#b08b36';else if(o.type==='Sprite2D'||o.type==='AnimatedSprite2D')fill='#5a4d83';else if(o.type==='Area2D')fill='#704b70';ctx.fillStyle=fill;ctx.strokeStyle=o===state.selected?'#69b5ff':'#496476';ctx.lineWidth=(o===state.selected?2:1)/state.zoom;ctx.fillRect(-o.w/2,-o.h/2,o.w,o.h);ctx.strokeRect(-o.w/2,-o.h/2,o.w,o.h);if(o.type==='TileMap'||o.type==='TileMapLayer'){const ts=Number(o.properties?.tileSize)||32;for(const [k,v] of Object.entries(tileCells(o))){if(!v)continue;const [cx,cy]=k.split(',').map(Number);ctx.fillStyle='#3f704d';ctx.fillRect(-o.w/2+cx*ts,-o.h/2+cy*ts,ts,ts);ctx.strokeStyle='#62856c';ctx.strokeRect(-o.w/2+cx*ts,-o.h/2+cy*ts,ts,ts);}}if(o.type==='AnimatedSprite2D'){const frames=Math.max(1,Number(o.properties?.frames)||4),dur=Math.max(.03,Number(o.properties?.frameDuration)||.14),f=Math.floor((state.runtime.animationTime||0)/dur)%frames;ctx.fillStyle=f%2?'#8064ad':'#a078c9';ctx.fillRect(-o.w/2+4,-o.h/2+4,o.w-8,o.h-8);ctx.fillStyle='#fff';ctx.font=`${Math.max(9,10/state.zoom)}px ui-monospace`;ctx.fillText(`${f+1}/${frames}`,-o.w/2+6,4);}if(o.type==='River'){ctx.strokeStyle='#7ac8ef';ctx.lineWidth=1.5/state.zoom;for(let y=-o.h/2+15;y<o.h/2;y+=18){ctx.beginPath();ctx.moveTo(-o.w/2+8,y);ctx.quadraticCurveTo(0,y-6,o.w/2-8,y);ctx.stroke();}}ctx.restore();}
function godotQuote(s){return JSON.stringify(String(s));}
function godotValue(v){if(v&&v.__type==='Vector2')return `Vector2(${v.x}, ${v.y})`;if(v&&v.__type==='Vector2i')return `Vector2i(${v.x}, ${v.y})`;if(v&&v.__type==='ExtResource')return `ExtResource("${v.id}")`;if(v&&v.__type==='SubResource')return `SubResource("${v.id}")`;if(typeof v==='string')return godotQuote(v);if(typeof v==='boolean'||typeof v==='number')return String(v);if(v===null)return 'null';return godotQuote(JSON.stringify(v));}
function sceneToTscn(){const root=rootForScene(state.scene);const nodes=[root,...state.scene.nodes];const idMap=new Map(nodes.map(n=>[n.id,n]));const namePath=n=>{if(!n||n===root)return '.';const p=n.parent?idMap.get(n.parent):root;return p===root?n.name:n.name;};let out='[gd_scene load_steps=1 format=3]\\n\\n';out+=`[node name=${godotQuote(root.name)} type=${godotQuote(root.type)}]\\n\\n`;for(const n of state.scene.nodes){const parent=n.parent&&idMap.has(n.parent)?(idMap.get(n.parent)===root?'.':idMap.get(n.parent).name):'.';out+=`[node name=${godotQuote(n.name)} type=${godotQuote(n.type)} parent=${godotQuote(parent)}]\\n`;if(n.x||n.y)out+=`position = Vector2(${n.x}, ${n.y})\\n`;if(n.rotation)out+=`rotation = ${n.rotation*Math.PI/180}\\n`;if(n.visible===false)out+='visible = false\\n';for(const [k,v] of Object.entries(n.properties||{})){if(['position','rotation','scale','visible'].includes(k))continue;out+=`${k} = ${godotValue(v)}\\n`;}out+='\\n';}return out.replace(/\\\\n/g,'\\n');}

function buildResourceModel(){
  state.projectModel.resources=[]; state.projectModel.scripts=[];
  for(const p of state.files){const e=ext(p);if(e==='.gd')state.projectModel.scripts.push({path:p,status:'partial',reason:'Script source preserved; execution stays in Godot runtime.'});
    if(['.tres','.res','.png','.jpg','.jpeg','.webp','.svg','.ogg','.wav','.mp3','.ttf','.woff','.woff2'].includes(e))state.projectModel.resources.push({path:p,type:e.slice(1),status:e==='.tres'||e==='.res'?'partial':'external'});}
}
function ninjaProjectText(){state.projectModel.project=clone(state.project);state.projectModel.scenes=state.projectModel.scenes.filter(s=>s.path!==state.scene.path);state.projectModel.scenes.push(clone(state.scene));buildResourceModel();return JSON.stringify(state.projectModel,null,2);}
function saveNinjaProject(){const blob=new Blob([ninjaProjectText()],{type:'application/json'});download(blob,'project.ninja.json');state.dirty=false;$('dirtyState').textContent='';log('Ninja project model saved.');}
async function exportProject(){try{const writer=new ZipWriter(new BlobWriter('application/zip'));const project=`; Generated by Ninja Engine\nconfig_version=5\n\n[application]\nconfig/name=${godotQuote(state.project.name||'Ninja Project')}\n\n[run]\nmain_scene=${godotQuote('res://'+(state.scene.name||'Main')+'.tscn')}\n\n[display]\nwindow/size/viewport_width=1100\nwindow/size/viewport_height=680\n`;await writer.add('project.godot',new BlobReader(new Blob([project])));await writer.add(`${state.scene.name||'Main'}.tscn`,new BlobReader(new Blob([sceneToTscn()])));await writer.add('ninja/project.ninja.json',new BlobReader(new Blob([ninjaProjectText()])));const blob=await writer.close();download(blob,'NinjaEngine_Godot_Project.zip');log('Godot 4 starter project + Ninja model exported.');}catch(e){log(`Export failed: ${e.message}`,'error');}}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function tick(now){const dt=Math.min(.05,(now-state.last)/1000);state.last=now;state.frame++;state.runtime.animationTime=(state.runtime.animationTime||0)+dt;updateRuntime(dt);if(state.frame%12===0){state.fps=Math.round(1/dt);$('fps').textContent=state.fps;const mem=performance.memory?.usedJSHeapSize;if(mem)$('memory').textContent=archiveSizeLabel(mem);if($('debugger'))$('debugger').innerHTML=state.playing?`<div><i>●</i> Runtime: running</div><div>Entities: ${state.runtime.entities.size}</div><div>Areas: ${state.runtime.areas.size}</div><div>Events: ${state.runtime.events.slice(0,8).map(escapeHtml).join('<br>')||'No area events.'}</div>`:'<div><i>●</i> Runtime stopped.</div>';}draw();requestAnimationFrame(tick);}
refreshConnections();
setScene({path:'',name:'Main',root:node('Node2D','Main',0,0,0,0,''),nodes:[]});state.scene.root.id='root';renderAll();draw();requestAnimationFrame(tick);
